#!/bin/bash

# Turn ports on
/usr/bin/firewall-offline-cmd --port 110:tcp --port 143:tcp --port 993:tcp --port 995:tcp --port 4190:tcp > /dev/null 2>&1
/bin/systemctl try-restart firewalld > /dev/null 2>&1

exit 0
